modules:
  - name: "antigravity"
    path: "antigravity"
    hosts:
      - HOME-DESKTOP
  - name: "bashrc"
    path: "bash"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "zsh"
    path: "zsh"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "fish"
    path: "fish"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
  - name: "starship"
    path: "starship"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "shell-utils"
    path: "shell-utils"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "direnv"
    path: "direnv"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "git"
    path: "git"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "vim"
    path: "vim"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "nvim"
    path: "nvim"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "tmux"
    path: "tmux"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "ssh"
    path: "ssh"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
      - WORK-MACBOOK
      - CODESPACES
  - name: "kitty"
    path: "kitty"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
  - name: "rofi"
    path: "rofi"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
  - name: "hyprland"
    path: "hyprland"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
  - name: "wayvnc"
    path: "wayvnc"
    hosts:
      - HOME-DESKTOP
      - ASUS-LAPTOP
