modules:
  - name: "antigravity"
    path: "antigravity"
    # target: "$HOME"  # Optional: specify default target for all hosts
    hosts:
      - HOME-DESKTOP # Uses $HOME by default
  - name: "bashrc"
    path: "bash"
    hosts:
      - HOME-DESKTOP
  - name: "vim"
    path: "vim"
    hosts:
      - HOME-DESKTOP
  - name: "zsh"
    path: "zsh"
    hosts:
      - HOME-DESKTOP
  - name: "fish"
    path: "fish"
    hosts:
      - HOME-DESKTOP
  - name: "direnv"
    path: "direnv"
    hosts:
      - HOME-DESKTOP
  - name: "kitty"
    path: "kitty"
    hosts:
      - HOME-DESKTOP
  - name: "rofi"
    path: "rofi"
    hosts:
      - HOME-DESKTOP
  - name: "hyprland"
    path: "hyprland"
    hosts:
      - HOME-DESKTOP
  - name: "wayvnc"
    path: "wayvnc"
    hosts:
      - HOME-DESKTOP
  - name: "git"
    path: "git"
    hosts:
      - HOME-DESKTOP
